# app_text.py

TEXTS = {
    "brand_name": "MANTHAN",
    "site_title": "MANTHAN - Mental Health Platform",
    "welcome": "Welcome to the Forum!",
    "hello_user": "Hello, {user}!",
    "not_logged_in": "You are not logged in",
    "login": "Login",
    "register": "Register",
    "logout": "Logout",
    "home": "Home",
    "guided_support": "Guided Support",
    "stress_relief": "Stress Relief",
    "anxiety_help": "Anxiety Help",
    "motivation_tips": "Motivation Tips",
    "document": "Document",
    "profile": "Profile",
    "view_profile": "View Profile",
    "edit_profile": "Edit Profile",
    "forum": "Forum",
    "exam_stress": "Exam Stress",
    "relationships": "Relationships",
    "sleep_issues": "Sleep Issues",
    "wellness_tools": "Wellness Tools",
    "meditation": "Meditation",
    "resources": "Resources",
    "articles": "Articles",
    "videos": "Videos",
    "guides": "Guides",
    "settings": "Settings",
    "preferences": "Preferences",
    "privacy": "Privacy",
    "how_are_you": "How are you feeling today?",
    "anxious": "Anxious",
    "stressed": "Stressed",
    "lonely": "Lonely",
    "fine": "Fine",
    "anxiety_tip": "You might be experiencing anxiety",
    "breathing_ex": "🌬️ Try a breathing exercise",
    "coping_strategies": "📖 Read coping strategies",
    "call_helpline": "☎️ Call a helpline",
    "feeling_stressed": "Feeling stressed?",
    "stress_tips": "🧘 Do 5 min meditation<br>🎶 Listen to calming audio",
    "feeling_lonely": "Feeling lonely?",
    "lonely_tips": "🤝 Join our Peer Forum<br>📱 Connect with community",
    "great_to_hear": "Great to hear!",
    "positive_tip": "💪 Stay positive 🌟 Share a smile today",
    "health_journey": "Your Health Journey Starts Here",
    "health_journey_desc": "Connect with a supportive community, get expert advice, and find answers to your health questions in a safe, moderated environment.",
    "search": "Search",
    "toolkit": "Your Mental Health Toolkit❤️",
    "heart_health": "Heart Health",
    "mental_health": "Mental Health",
    "fitness": "Fitness & Exercise",
    "nutrition": "Nutrition",
    "womens_health": "Women's Health",
    "general_medicine": "General Medicine",
    "daily_tips": "💡 Daily Health Tips",
    "hydration": "Hydration Reminder: Aim for 8 glasses of water daily...",
    "sleep_quality": "Sleep Quality: Maintain a consistent sleep schedule...",
    "movement": "Movement Matters: Take a 10-minute walk after meals...",
    "poll": "Anonymous Poll",
    "poll_q": "Do you feel academic pressure daily?",
    "yes": "Yes",
    "no": "No",
    "submit": "Submit",
    "thanks_vote": "✅ Thanks for voting! (Results hidden)",
    "community_stats": "Community Stats",
    "active_members": "Active Members",
    "forum_posts": "Forum Posts",
    "experts": "Expert Contributors",
    "support": "Community Support",
    "featured_experts": "Featured Health Experts",
    "daily_challenge": "🌟 Daily Challenge",
    "daily_challenge_text": "Try 5 minutes of meditation today.",
    "challenge_note": "Complete it and feel refreshed!",
    "trending": "Trending Topics",
    "health_disclaimer": "🚨 Health Disclaimer",
    "disclaimer_text": "Information shared in this forum is for educational purposes only...",
    "about": "About",
    "description": "Manthan Health Forum provides digital mental health & psychological support for students in higher education",
    "quick_links": "Quick Links",
    "counsellor_booking": "Counsellor Booking",
    "peer_forum": "Peer Forum",
    "languages": "Languages",
    "hindi": "हिन्दी",
    "english": "English",
    "urdu": "Urdu",
    "tamil": "Tamil",
    "contact": "Contact",
    "email": "Email: support@manthan.edu",
    "helpline": "Helpline: +91 12345 67890",
    "copyright": "© 2025 Manthan Health Forum. All Rights Reserved."
}

TEXTS_HI = {
    "brand_name": "मंथन",
    "site_title": "मंथन - मानसिक स्वास्थ्य मंच",
    "welcome": "फोरम में आपका स्वागत है!",
    "hello_user": "नमस्ते, {user}!",
    "not_logged_in": "आप लॉगिन नहीं हैं",
    "login": "लॉगिन",
    "register": "रजिस्टर",
    "logout": "लॉगआउट",
    "home": "होम",
    "guided_support": "मार्गदर्शित सहायता",
    "stress_relief": "तनाव मुक्ति",
    "anxiety_help": "चिंता सहायता",
    "motivation_tips": "प्रेरणा सुझाव",
    "document": "दस्तावेज़",
    "profile": "प्रोफ़ाइल",
    "view_profile": "प्रोफ़ाइल देखें",
    "edit_profile": "प्रोफ़ाइल संपादित करें",
    "forum": "फोरम",
    "exam_stress": "परीक्षा तनाव",
    "relationships": "संबंध",
    "sleep_issues": "नींद की समस्याएँ",
    "wellness_tools": "स्वास्थ्य उपकरण",
    "meditation": "ध्यान",
    "resources": "संसाधन",
    "articles": "लेख",
    "videos": "वीडियो",
    "guides": "मार्गदर्शिकाएँ",
    "settings": "सेटिंग्स",
    "preferences": "वरीयताएँ",
    "privacy": "गोपनीयता",
    "how_are_you": "आज आप कैसा महसूस कर रहे हैं?",
    "anxious": "चिंतित",
    "stressed": "तनावग्रस्त",
    "lonely": "अकेला",
    "fine": "ठीक",
    "anxiety_tip": "आप चिंता का अनुभव कर रहे हो सकते हैं",
    "breathing_ex": "🌬️ श्वास व्यायाम करें",
    "coping_strategies": "📖 मुकाबला रणनीतियाँ पढ़ें",
    "call_helpline": "☎️ हेल्पलाइन पर कॉल करें",
    "feeling_stressed": "क्या आप तनावग्रस्त हैं?",
    "stress_tips": "🧘 5 मिनट ध्यान करें<br>🎶 शांत संगीत सुनें",
    "feeling_lonely": "क्या आप अकेले हैं?",
    "lonely_tips": "🤝 हमारे पीयर फोरम से जुड़ें<br>📱 समुदाय से जुड़ें",
    "great_to_hear": "यह सुनकर अच्छा लगा!",
    "positive_tip": "💪 सकारात्मक रहें 🌟 आज एक मुस्कान साझा करें",
    "health_journey": "आपकी स्वास्थ्य यात्रा यहीं से शुरू होती है",
    "health_journey_desc": "एक सहयोगी समुदाय से जुड़ें, विशेषज्ञ सलाह लें, और सुरक्षित वातावरण में अपने स्वास्थ्य प्रश्नों के उत्तर पाएं।",
    "search": "खोजें",
    "toolkit": "आपका मानसिक स्वास्थ्य टूलकिट ❤️",
    "heart_health": "हृदय स्वास्थ्य",
    "mental_health": "मानसिक स्वास्थ्य",
    "fitness": "फ़िटनेस और व्यायाम",
    "nutrition": "पोषण",
    "womens_health": "महिला स्वास्थ्य",
    "general_medicine": "सामान्य चिकित्सा",
    "daily_tips": "💡 दैनिक स्वास्थ्य सुझाव",
    "hydration": "हाइड्रेशन अनुस्मारक: प्रतिदिन 8 गिलास पानी पिएं...",
    "sleep_quality": "नींद की गुणवत्ता: 7-9 घंटे की नींद का पालन करें...",
    "movement": "गतिविधि महत्वपूर्ण है: भोजन के बाद 10 मिनट टहलें...",
    "poll": "गुमनाम सर्वेक्षण",
    "poll_q": "क्या आप रोज़ अकादमिक दबाव महसूस करते हैं?",
    "yes": "हाँ",
    "no": "नहीं",
    "submit": "सबमिट",
    "thanks_vote": "✅ मतदान के लिए धन्यवाद! (परिणाम छिपाए गए)",
    "community_stats": "सामुदायिक आँकड़े",
    "active_members": "सक्रिय सदस्य",
    "forum_posts": "फोरम पोस्ट",
    "experts": "विशेषज्ञ योगदानकर्ता",
    "support": "सामुदायिक सहायता",
    "featured_experts": "विशेष स्वास्थ्य विशेषज्ञ",
    "daily_challenge": "🌟 दैनिक चुनौती",
    "daily_challenge_text": "आज 5 मिनट ध्यान करें।",
    "challenge_note": "इसे पूरा करें और ताज़गी महसूस करें!",
    "trending": "प्रवृत्त विषय",
    "health_disclaimer": "🚨 स्वास्थ्य अस्वीकरण",
    "disclaimer_text": "इस फोरम में साझा जानकारी केवल शैक्षिक उद्देश्यों के लिए है...",
    "about": "परिचय",
    "description": "मंथन स्वास्थ्य फोरम उच्च शिक्षा के छात्रों के लिए डिजिटल मानसिक स्वास्थ्य और मनोवैज्ञानिक सहायता प्रदान करता है।",
    "quick_links": "त्वरित लिंक",
    "counsellor_booking": "काउंसलर बुकिंग",
    "peer_forum": "पीयर फोरम",
    "languages": "भाषाएँ",
    "hindi": "हिन्दी",
    "english": "अंग्रेज़ी",
    "urdu": "उर्दू",
    "tamil": "तमिल",
    "contact": "संपर्क",
    "email": "ईमेल: support@manthan.edu",
    "helpline": "हेल्पलाइन: +91 12345 67890",
    "copyright": "© 2025 मंथन स्वास्थ्य फोरम. सर्वाधिकार सुरक्षित।"
}